### ISSUE TITLE
Capacity Testing for StormClustering

### ISSUE THREAD

**Issue by shethkushal** [airavata-courses/TeamAurora#16]
Plot graphs for capacity testing: Storm Clustering Service

**Comment by SrikanthHolavanahalli** [comment]
[Storm Clustering.zip](https://github.com/airavata-courses/TeamAurora/files/545586/Storm.Clustering.zip)

**Comment by SrikanthHolavanahalli** [comment]
Latest results
[Storm Clustering.zip](https://github.com/airavata-courses/TeamAurora/files/545590/Storm.Clustering.zip)
