### ISSUE TITLE
Capacity Testing for Storm Detector

### ISSUE THREAD

**Issue by shethkushal** [airavata-courses/TeamAurora#17]
Plot graphs for capacity testing: Storm Detector Service

**Comment by SrikanthHolavanahalli** [comment]
![load testing](https://cloud.githubusercontent.com/assets/16628190/19616714/828dd19c-97e8-11e6-982e-2ae12bbb6110.png)

**Comment by SrikanthHolavanahalli** [comment]
[StormDetector Complete Load Testing.zip](https://github.com/airavata-courses/TeamAurora/files/545585/StormDetector.Complete.Load.Testing.zip)
