### ISSUE TITLE
Finalize UI and Backend languages/frameworks

### ISSUE THREAD

**Issue by pratiksanghvi** [airavata-courses/TeamAurora#8]
Currently we have decided to use Java and Python. This issue is created to finalize which back-end languages to use and why. 
Also decide on which Python framework to use: Flask or Django?

**Comment by KaushalVikrant** [comment]
Let's start with Django because it is scalable, efficient and secure. Django also provides more functionality in comparison to Flask.

**Comment by shethkushal** [comment]
Finalized Java, Python for backend and JavaScript, HTML for frontend
